csv_file_path: './shopping/shopping_trends.csv'
log_file_path: './etl_process.log'
db_config:
  user: 'Elliot'
  password: 'pwd'
  host: 'localhost'
  port: 5432
  database: 'shoppingpipeline'
  url: 'postgresql://Elliot:pwd@localhost:5432/'
